export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = "COUNTER_DECREMENT"
export const INPUT_SEARCH = "INPUT_SEARCH"
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const FETCH_DATA = "FETCH_DATA"